### ISSUE TITLE
Error when running ipython notebook

### ISSUE THREAD

**Issue by weiliu620** [pandegroup/reaction_prediction_seq2seq#2]
I can run the inference Bash script without error now. But when I run the ipython notebook under `predictions` folder for evaluation, I got the following error:
```
ZeroDivisionError                         Traceback (most recent call last)
<ipython-input-5-24745264db7b> in <module>()
     14 result_path = os.path.join(cwd, 'beam_1_test_results')
     15 
---> 16 evaluate_beam_by_rxn_class(pred_path, target_path, source_path, result_path)
     17 
     18 # beams (ie beam width != 1). Write the formatted beam target and beam source files in a temp dir

<ipython-input-4-b44962c4bf02> in evaluate_beam_by_rxn_class(beam_prediction_path, beam_ground_truth_path, beam_source_path, result_path)
    257   # calculate metric and print correct/incorrect examples for overall array
    258   _evaluate_array(prediction_array, ground_truth_array, test_source_array,
--> 259                   result_path, reaction_class=None)
    260 
    261   # find array of unique reaction classes from test source

<ipython-input-4-b44962c4bf02> in _evaluate_array(prediction_array, ground_truth_array, test_source_array, result_path, reaction_class)
    181     # calculate final metrics
    182     num_examples_with_em = sum(x > 0 for x in num_em_per_example_list)
--> 183     average_em = num_examples_with_em / num_examples  # this is the top k accuracy
    184 
    185     # write result file

ZeroDivisionError: division by zero
```
The error happened at the last cell in the notebook. 

Did I miss anything?

(as a side note, I'm new to chemical and not sure the difference between the inference step and the prediction step. It looks the notebook does not run any TF code, so where it used the trained model?)

**Comment by bowenliu16** [comment]
Hmm, could you please tell me the contents of your predictions folder? The inference and prediction are the same. The infer scripts use the model to make the predictions based on the test examples, and then the evaluation scripts produce the accuracy metrics. The current code evaluates on all the results (beam size = 1, 3, 5, 10, 20, 50), so it expects all the corresponding prediction files to be in the predictions folder
