### ISSUE TITLE
Can't use jul_5_2017 checkpoint

### ISSUE THREAD

**Issue by eventfulsean** [pandegroup/reaction_prediction_seq2seq#4]
Hi!

When I train using the jul_5_2017 checkpoint I get the following error:
`InvalidArgumentError (see above for traceback): Unsuccessful TensorSliceReader constructor: Failed to get matching files on /home/bowen/pycharm_deployment_directory/synthesis/prototype_models/google_seq2seq_public_upload/reaction_prediction_seq2seq/model_working_directory/jul_5_2017_1/model.ckpt-44001: Not found: /home/bowen/pycharm_deployment_directory/synthesis/prototype_models/google_seq2seq_public_upload/reaction_prediction_seq2seq/model_working_directory/jul_5_2017_1; No such file or directory`

Looking into the "checkpoint" file, there are pointers to a non-existent path and checkpoint file.

```
model_checkpoint_path: "/home/bowen/pycharm_deployment_directory/synthesis/prototype_models/google_seq2seq_public_upload/reaction_prediction_seq2seq/model_working_directory/jul_5_2017_1/model.ckpt-44001"
all_model_checkpoint_paths: "/home/bowen/pycharm_deployment_directory/synthesis/reaction_translator/dataset_patent_filtered/model_working_dir/google_seq2seq/jul_5_2017_1/model.ckpt-44001"                                                         
```                                                                                                                                                                                     
I'm not sure where this file is. Editing the 'checkpoint' file to point to other files in the checkpoint tarball got me:
`Data loss: not an sstable (bad magic number): perhaps your file is in a different file format and you need to use a different restore operator?
`

Could you help?

Thanks!
Sean

**Comment by bowenliu16** [comment]
Hi Sean!
I think the current checkpoint files can only be used for inference to reproduce the results reported in the paper. If you want to train a new model, then you should start a new run, and not resume from this checkpoint. In that case, you should modify the MODEL_DIR value in the google_seq2seq_train_jul_5_2017_1.sh file to a new model name
Hope this helps!
