### ISSUE TITLE
Availability of baseline model

### ISSUE THREAD

**Issue by rmcgibbo** [pandegroup/reaction_prediction_seq2seq#5]
Hi @bowenliu16!

The paper associated with this repository describes a baseline model with "2868 unique retrosynthetic reaction rules, defined by SMARTS strings." Is that baseline model available in this repository or elsewhere?

Thanks!

**Comment by bowenliu16** [comment]
Hi @rmcgibbo!
The baseline that we adapted can be found here: 
https://github.com/connorcoley/ochem_predict_nn
