### ISSUE TITLE
Details about the dataset.

### ISSUE THREAD

**Issue by QuickLearner171998** [pandegroup/reaction_prediction_seq2seq#8]
Hi,
I wanted to know from where did you get the dataset. How can I convert a molecule to SMILES format and what all preprocessing is needed?
It would be very helpful if you can provide the links for the dataset.

Thanks

**Comment by bowenliu16** [comment]
Hi, the dataset used was from: https://pubs.acs.org/doi/10.1021/acs.jcim.6b00564

**Comment by QuickLearner171998** [comment]
Thanks!!
